Repository TokkoLabs/jopi.js, pull requests merged in 2020-07, with the labels that each got.

#210 Jj 72 crear GitHub actions
  .github/workflows/integration-tests.yml
  .github/workflows/publish.yml
  package.json
  packages/Text/package.json
  packages/alert/package.json
  packages/badge/package.json
  packages/box/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/collapsible/package.json
  packages/datepicker/package.json
  packages/drawer/package.json
  packages/dropdown/package.json
  packages/hooks/package.json
  packages/icons/package.json
  packages/image/package.json
  packages/input/package.json
  packages/jopijs/package.json
  packages/label/package.json
  packages/list/package.json
  packages/loader/package.json
  packages/modal/package.json
  packages/radio/package.json
  packages/switch/package.json
  packages/table/package.json
  packages/tabs/package.json
  packages/theme/package.json
Labels: enhancement

#215 JJ-76 fix to GitHub actions
  .github/workflows/publish.yml
  README.md
  yarn.lock
Labels: bug

#216 New Jopi Version
  .github/workflows/publish.yml
  README.md
Labels: bug

#217 JJ-76 Fix to Github Actions - Steps fixes
  .github/workflows/publish.yml
Labels: bug

#218 New Jopi Version
  .github/workflows/publish.yml
Labels: bug

#219 JJ-76 Fix to Github Actions - SSH KEY
  .github/workflows/publish.yml
Labels: bug

#220 New Jopi Version
  .github/workflows/publish.yml
Labels: bug

#221 JJ-76 Fix to Github Actions - Change publish branch
  .github/workflows/publish.yml
Labels: bug

#222 JJ-76 Fix to Github Actions - Return the branch to master
  .github/workflows/publish.yml
Labels: bug

#224 JJ-76 Fix to GitHub actions
  .github/workflows/publish.yml
  README.md
Labels: bug

#225 New Jopi Version
  .github/workflows/publish.yml
  README.md
Labels: bug

#226 JJ-76 Fix to Github Actions - Change Again publish branch to development
  .github/workflows/publish.yml
Labels: bug

#227 JJ-76 Fix to Github Actions - Return to master branch
  .github/workflows/publish.yml
Labels: bug

#229 JJ-76 Fix to Github Actions - Run only the test on master
  .github/workflows/publish.yml
Labels: bug

#230 New Jopi Version
  .github/workflows/publish.yml
Labels: bug

#231 JJ-76 Fix to Github Actions - Lerna update package on publish step
  .github/workflows/publish.yml
Labels: bug

#232 New Jopi Version
  .github/workflows/publish.yml
Labels: bug

#233 JJ-76 Fix to Github Actions - Change the GH action to pull_request
  .github/workflows/publish.yml
Labels: bug

#238 JJ-76 Fix to Github Actions - Lerna update packages is removed
  .github/workflows/publish.yml
Labels: bug

#240 JJ-76 Fix to Github Actions - Update jest snapshots
  .github/workflows/publish.yml
  packages/Text/test/__snapshots__/Text.spec.js.snap
  packages/alert/test/__snapshots__/Alert.spec.js.snap
  packages/badge/test/__snapshots__/Badge.spec.js.snap
  packages/box/test/__snapshots__/Box.spec.js.snap
  packages/button/test/__snapshots__/Button.spec.js.snap
  packages/checkbox/test/__snapshots__/Checkbox.spec.js.snap
  packages/collapsible/test/__snapshots__/Collapsible.spec.js.snap
  packages/dropdown/test/__snapshots__/Dropdown.spec.js.snap
  packages/image/test/__snapshots__/Image.spec.js.snap
  packages/input/test/__snapshots__/Input.spec.js.snap
  packages/label/test/__snapshots__/Label.spec.js.snap
  packages/list/test/__snapshots__/List.spec.js.snap
  packages/loader/test/__snapshots__/Loader.spec.js.snap
  packages/modal/test/__snapshots__/Modal.spec.js.snap
  packages/radio/test/__snapshots__/Radio.spec.js.snap
  packages/switch/test/__snapshots__/Switch.spec.js.snap
  packages/table/test/__snapshots__/Table.spec.js.snap
  packages/tabs/test/__snapshots__/Tabs.spec.js.snap
Labels: bug

#241 New Jopi Version
  .github/workflows/publish.yml
  packages/Text/test/__snapshots__/Text.spec.js.snap
  packages/alert/test/__snapshots__/Alert.spec.js.snap
  packages/badge/test/__snapshots__/Badge.spec.js.snap
  packages/box/test/__snapshots__/Box.spec.js.snap
  packages/button/test/__snapshots__/Button.spec.js.snap
  packages/checkbox/test/__snapshots__/Checkbox.spec.js.snap
  packages/collapsible/test/__snapshots__/Collapsible.spec.js.snap
  packages/dropdown/test/__snapshots__/Dropdown.spec.js.snap
  packages/image/test/__snapshots__/Image.spec.js.snap
  packages/input/test/__snapshots__/Input.spec.js.snap
  packages/label/test/__snapshots__/Label.spec.js.snap
  packages/list/test/__snapshots__/List.spec.js.snap
  packages/loader/test/__snapshots__/Loader.spec.js.snap
  packages/modal/test/__snapshots__/Modal.spec.js.snap
  packages/radio/test/__snapshots__/Radio.spec.js.snap
  packages/switch/test/__snapshots__/Switch.spec.js.snap
  packages/table/test/__snapshots__/Table.spec.js.snap
  packages/tabs/test/__snapshots__/Tabs.spec.js.snap
Labels: bug

#243 New Jopi Version
  packages/Text/test/__snapshots__/Text.spec.js.snap
  packages/alert/test/__snapshots__/Alert.spec.js.snap
  packages/badge/test/__snapshots__/Badge.spec.js.snap
  packages/box/test/__snapshots__/Box.spec.js.snap
  packages/button/test/__snapshots__/Button.spec.js.snap
  packages/checkbox/test/__snapshots__/Checkbox.spec.js.snap
  packages/collapsible/test/__snapshots__/Collapsible.spec.js.snap
  packages/dropdown/test/__snapshots__/Dropdown.spec.js.snap
  packages/image/test/__snapshots__/Image.spec.js.snap
  packages/input/test/__snapshots__/Input.spec.js.snap
  packages/jopijs/src/index.js
  packages/label/test/__snapshots__/Label.spec.js.snap
  packages/list/test/__snapshots__/List.spec.js.snap
  packages/loader/test/__snapshots__/Loader.spec.js.snap
  packages/modal/test/__snapshots__/Modal.spec.js.snap
  packages/radio/test/__snapshots__/Radio.spec.js.snap
  packages/switch/test/__snapshots__/Switch.spec.js.snap
  packages/table/test/__snapshots__/Table.spec.js.snap
  packages/tabs/test/__snapshots__/Tabs.spec.js.snap
  packages/textarea/.npmignore
  packages/textarea/package.json
  packages/textarea/src/Textarea.stories.js
  packages/textarea/src/index.js
  packages/textarea/test/Textarea.spec.js
  packages/textarea/test/__snapshots__/Textarea.spec.js.snap
Labels: bug, enhancement

#246 JJ-76 Fix GitHub Actions - get git & ssh info
  .github/workflows/publish.yml
Labels: bug, enhancement

#247 New Jopi Version
  .github/workflows/publish.yml
Labels: bug, enhancement

#248 JJ-76 Fix GitHub Actions - separate git, shh and lerna
  .github/workflows/publish.yml
Labels: bug, enhancement

#250 New Jopi Version
  .github/workflows/publish.yml
Labels: bug, enhancement

#251 add whoami & ls
  .github/workflows/publish.yml
Labels: bug, enhancement

#252 New Jopi Version
  .github/workflows/publish.yml
Labels: bug, enhancement

#253 add ssh key to lerna - more ssh info
  .github/workflows/publish.yml
Labels: bug, enhancement

#254 New Jopi Version
  .github/workflows/publish.yml
Labels: bug, enhancement

#255 New Jopi Version
  .github/workflows/publish.yml
Labels: bug, enhancement

#256 New Jopi Version
  .github/workflows/publish.yml
Labels: bug, enhancement

#257 JJ-73 Create New Textarea Component add "textarea" to jopijs/package.json dependencies
  packages/jopijs/package.json
Labels: bug

#258 New Jopi Version
  packages/jopijs/package.json
Labels: bug, enhancement

#259 Fix GitHub actions 2
  .github/workflows/publish.yml
Labels: bug, enhancement

#260 go back with NPM_TOKEN var name
  .github/workflows/publish.yml
Labels: bug, enhancement

#261 changes in publish.yml
  .github/workflows/publish.yml
  packages/textarea/test/Textarea.spec.js
  packages/textarea/test/__snapshots__/Textarea.spec.js.snap
Labels: bug, enhancement

#266 Add 'update' to 'lerna version' command & merge build y publish jobs
  .github/workflows/publish.yml
  packages/textarea/test/Textarea.spec.js
  packages/textarea/test/__snapshots__/Textarea.spec.js.snap
Labels: bug, enhancement

#267 Add lerna globally
  .github/workflows/publish.yml
Labels: bug

#268 Remove 'update' from 'lerna version' step
  .github/workflows/publish.yml
Labels: bug

#269 Split jobs in 'build' and 'publish' again
  .github/workflows/publish.yml
Labels: bug, enhancement

#270 Look up for lib folder in Alert package
  .github/workflows/publish.yml
Labels: bug, enhancement

#271 Unit again build & publish
  .github/workflows/publish.yml
Labels: bug, enhancement

#273 Fix Github Actions - Unite build and publish jobs
  .github/workflows/publish.yml
  packages/Text/package.json
  packages/alert/package.json
  packages/badge/package.json
  packages/box/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/collapsible/package.json
  packages/datepicker/package.json
  packages/drawer/package.json
  packages/dropdown/package.json
  packages/hooks/package.json
  packages/icons/package.json
  packages/image/package.json
  packages/input/package.json
  packages/jopijs/package.json
  packages/label/package.json
  packages/list/package.json
  packages/loader/package.json
  packages/modal/package.json
  packages/radio/package.json
  packages/switch/package.json
  packages/table/package.json
  packages/tabs/package.json
  packages/textarea/package.json
  packages/textarea/test/Textarea.spec.js
  packages/textarea/test/__snapshots__/Textarea.spec.js.snap
  packages/theme/package.json
Labels: bug, enhancement

#274 New Jopi Version
  .github/workflows/publish.yml
  packages/Text/package.json
  packages/alert/package.json
  packages/badge/package.json
  packages/box/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/collapsible/package.json
  packages/datepicker/package.json
  packages/drawer/package.json
  packages/dropdown/package.json
  packages/hooks/package.json
  packages/icons/package.json
  packages/image/package.json
  packages/input/package.json
  packages/jopijs/package.json
  packages/label/package.json
  packages/list/package.json
  packages/loader/package.json
  packages/modal/package.json
  packages/radio/package.json
  packages/switch/package.json
  packages/table/package.json
  packages/tabs/package.json
  packages/textarea/package.json
  packages/textarea/test/Textarea.spec.js
  packages/textarea/test/__snapshots__/Textarea.spec.js.snap
  packages/theme/package.json
Labels: bug, enhancement

#276 Add merge-me-action
  .github/workflows/publish.yml
Labels: enhancement

#277 Add merge-me-action
  .github/workflows/publish.yml
  packages/Text/package.json
  packages/alert/package.json
  packages/badge/package.json
  packages/box/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/collapsible/package.json
  packages/datepicker/package.json
  packages/drawer/package.json
  packages/dropdown/package.json
  packages/hooks/package.json
  packages/icons/package.json
  packages/image/package.json
  packages/input/package.json
  packages/jopijs/package.json
  packages/label/package.json
  packages/list/package.json
  packages/loader/package.json
  packages/modal/package.json
  packages/radio/package.json
  packages/switch/package.json
  packages/table/package.json
  packages/tabs/package.json
  packages/textarea/package.json
  packages/theme/package.json
Labels: enhancement

#278 New Jopi Version
  .github/workflows/publish.yml
  packages/Text/package.json
  packages/alert/package.json
  packages/badge/package.json
  packages/box/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/collapsible/package.json
  packages/datepicker/package.json
  packages/drawer/package.json
  packages/dropdown/package.json
  packages/hooks/package.json
  packages/icons/package.json
  packages/image/package.json
  packages/input/package.json
  packages/jopijs/package.json
  packages/label/package.json
  packages/list/package.json
  packages/loader/package.json
  packages/modal/package.json
  packages/radio/package.json
  packages/switch/package.json
  packages/table/package.json
  packages/tabs/package.json
  packages/textarea/package.json
  packages/theme/package.json
Labels: enhancement
