Repository TokkoLabs/jopi.js, pull requests merged in 2021-01, with the labels that each got.

#508 Agrega la opcion de button disabled y agrega un z-index de 1000 en el…
  packages/button/src/Button.stories.js
  packages/modal/src/index.js
  packages/modal/test/__snapshots__/Modal.spec.js.snap
  packages/theme/src/index.js
Labels: bug, enhancement

#509 Agrega funcionalidad de cierre de alerts
  packages/alert/src/Alert.stories.js
  packages/alert/src/index.js
  packages/alert/test/__snapshots__/Alert.spec.js.snap
Labels: enhancement

#510 DT-424 Crear componente para paginado
  package.json
  packages/Text/src/Text.stories.js
  packages/alert/src/Alert.stories.js
  packages/badge/src/Badge.stories.js
  packages/box/src/Box.stories.js
  packages/button/src/Button.stories.js
  packages/checkbox/src/Checkbox.stories.js
  packages/collapsible/src/Collapsible.stories.js
  packages/datepicker/src/Datepicker.stories.js
  packages/drawer/src/Drawer.stories.js
  packages/dropdown/src/Dropdown.stories.js
  packages/icons/src/Icons.stories.js
  packages/image/src/Image.stories.js
  packages/input/src/Input.stories.js
  packages/label/src/Label.stories.js
  packages/list/src/List.stories.js
  packages/loader/src/Loader.stories.js
  packages/modal/src/Modal.stories.js
  packages/paginator/src/Paginator.stories.js
  packages/paginator/src/index.js
  packages/paginator/test/Paginator.spec.js
  packages/paginator/test/__snapshots__/Paginator.spec.js.snap
  packages/radio/src/Radio.stories.js
  packages/switch/src/Switch.stories.js
  packages/table/src/Table.stories.js
  packages/tabs/src/Tabs.stories.js
  packages/textarea/src/Textarea.stories.js
  yarn.lock
Labels: enhancement

#512 DT-424 Crear componente para el paginado
  packages/paginator/.npmignore
  packages/paginator/package.json
Labels: enhancement

#511 Documenta en Storybook la posibilidad de enviar true / false en la pr…
  packages/checkbox/src/Checkbox.stories.js
Labels: enhancement

#513 New Jopi version
  package.json
  packages/Text/src/Text.stories.js
  packages/alert/src/Alert.stories.js
  packages/alert/src/index.js
  packages/alert/test/__snapshots__/Alert.spec.js.snap
  packages/badge/src/Badge.stories.js
  packages/box/src/Box.stories.js
  packages/button/src/Button.stories.js
  packages/checkbox/src/Checkbox.stories.js
  packages/collapsible/src/Collapsible.stories.js
  packages/datepicker/src/Datepicker.stories.js
  packages/drawer/src/Drawer.stories.js
  packages/dropdown/src/Dropdown.stories.js
  packages/icons/src/Icons.stories.js
  packages/image/src/Image.stories.js
  packages/input/src/Input.stories.js
  packages/label/src/Label.stories.js
  packages/list/src/List.stories.js
  packages/loader/src/Loader.stories.js
  packages/modal/src/Modal.stories.js
  packages/modal/src/index.js
  packages/modal/test/__snapshots__/Modal.spec.js.snap
  packages/paginator/.npmignore
  packages/paginator/package.json
  packages/paginator/src/Paginator.stories.js
  packages/paginator/src/index.js
  packages/paginator/test/Paginator.spec.js
  packages/paginator/test/__snapshots__/Paginator.spec.js.snap
  packages/radio/src/Radio.stories.js
  packages/switch/src/Switch.stories.js
  packages/table/src/Table.stories.js
  packages/tabs/src/Tabs.stories.js
  packages/textarea/src/Textarea.stories.js
  packages/theme/src/index.js
  yarn.lock
Labels: enhancement

#516 Hot-fix Error New Jopi Version
  yarn.lock
Labels: bug

#517 Hot-fix Error New Jopi Version
  yarn.lock
Labels: bug

#518 DT-424 Crear componente para el paginado
  packages/jopijs/package.json
  packages/jopijs/src/index.js
Labels: bug

#519 Hot-fix Error New Jopi Version
  packages/jopijs/package.json
  packages/jopijs/src/index.js
Labels: bug

#524 Dt 508 fix paginator error condition and style
  docs/iframe.html
  docs/index.html
  docs/main.2c8141536592b962d551.bundle.js
  docs/main.2c8141536592b962d551.bundle.js.map
  docs/main.aa832e13b3dfff3e7dcf.bundle.js
  docs/main.ddcd5fdce967fac69a19.bundle.js
  docs/main.ec655174ba392fa34bdf.bundle.js
  docs/main.ec655174ba392fa34bdf.bundle.js.map
  docs/runtime~main.2c8141536592b962d551.bundle.js
  docs/runtime~main.2c8141536592b962d551.bundle.js.map
  docs/runtime~main.ec655174ba392fa34bdf.bundle.js
  docs/runtime~main.ec655174ba392fa34bdf.bundle.js.map
  docs/vendors~main.2c8141536592b962d551.bundle.js
  docs/vendors~main.2c8141536592b962d551.bundle.js.LICENSE.txt
  docs/vendors~main.2c8141536592b962d551.bundle.js.map
  docs/vendors~main.36f1a2ce84a5d443b9b7.bundle.js.LICENSE.txt
  docs/vendors~main.96c2d9ffcb2538cef8d3.bundle.js
  docs/vendors~main.96c2d9ffcb2538cef8d3.bundle.js.LICENSE.txt
  docs/vendors~main.ec655174ba392fa34bdf.bundle.js.LICENSE.txt
  docs/vendors~main.ec655174ba392fa34bdf.bundle.js.map
  packages/paginator/src/Paginator.stories.js
  packages/paginator/src/index.js
  packages/paginator/test/Paginator.spec.js
  packages/paginator/test/__snapshots__/Paginator.spec.js.snap
Labels: bug, enhancement

#525 Development - DT-508 fix paginador
  docs/iframe.html
  docs/index.html
  docs/main.2c8141536592b962d551.bundle.js
  docs/main.2c8141536592b962d551.bundle.js.map
  docs/main.aa832e13b3dfff3e7dcf.bundle.js
  docs/main.ddcd5fdce967fac69a19.bundle.js
  docs/main.ec655174ba392fa34bdf.bundle.js
  docs/main.ec655174ba392fa34bdf.bundle.js.map
  docs/runtime~main.2c8141536592b962d551.bundle.js
  docs/runtime~main.2c8141536592b962d551.bundle.js.map
  docs/runtime~main.ec655174ba392fa34bdf.bundle.js
  docs/runtime~main.ec655174ba392fa34bdf.bundle.js.map
  docs/vendors~main.2c8141536592b962d551.bundle.js
  docs/vendors~main.2c8141536592b962d551.bundle.js.LICENSE.txt
  docs/vendors~main.2c8141536592b962d551.bundle.js.map
  docs/vendors~main.36f1a2ce84a5d443b9b7.bundle.js.LICENSE.txt
  docs/vendors~main.96c2d9ffcb2538cef8d3.bundle.js
  docs/vendors~main.96c2d9ffcb2538cef8d3.bundle.js.LICENSE.txt
  docs/vendors~main.ec655174ba392fa34bdf.bundle.js.LICENSE.txt
  docs/vendors~main.ec655174ba392fa34bdf.bundle.js.map
  packages/paginator/src/Paginator.stories.js
  packages/paginator/src/index.js
  packages/paginator/test/Paginator.spec.js
  packages/paginator/test/__snapshots__/Paginator.spec.js.snap
Labels: bug, enhancement
